"""
bayesian_layer.py
-------------------
Combines Module 1's anomaly_score with Module 2's phishing_probability into
a single posterior probability of attack, using actual Bayes' rule — not a
weighted average dressed up as "Bayesian."

PUBLIC CONTRACT (do not rename):
    bayesian_risk_adjustment(anomaly_score, phishing_probability,
                              historical_attack_rate, prior_probability)
        -> final_risk_probability

===============================================================================
THE MATH (why this is genuine Bayesian updating, not a weighted sum)
===============================================================================
Bayes' rule, written in odds form, is:

    posterior_odds = prior_odds * likelihood_ratio

This holds exactly for a single piece of evidence. For two INDEPENDENT
pieces of evidence (a standard "naive Bayes" assumption — here, that the
network-behavior signal and the content/text signal are conditionally
independent given the true attack/legitimate label, which is reasonable:
a phishing email's wording and the network anomalies around its delivery
are generated by largely separate mechanisms), the posterior odds multiply
each evidence source's likelihood ratio in turn:

    posterior_odds = prior_odds * LR_anomaly * LR_phishing

We don't have raw class-conditional likelihoods P(evidence | attack) —
Module 1 and Module 2 hand us calibrated POSTERIOR probability estimates
(anomaly_score/100, phishing_probability) instead. But if we assume each of
those sub-models' outputs is itself a Bayes-updated posterior computed from
an implicit reference prior — the `historical_attack_rate` — we can invert
Bayes' rule to recover the implied likelihood ratio each one contributes:

    LR_i = odds(evidence_i) / odds(historical_attack_rate)

This is exactly how likelihood ratios are estimated in practice whenever you
only have a classifier's output probability rather than its underlying
class-conditional densities (the same trick used to combine diagnostic test
results in medicine, and in "log-opinion-pool" ensemble fusion).

Putting it together, entirely in log-odds (logit) space for numerical
stability — a sum in logit space is a product in odds space:

    logit(final) = logit(prior_probability)
                 + [ logit(anomaly_score/100)   - logit(historical_attack_rate) ]
                 + [ logit(phishing_probability) - logit(historical_attack_rate) ]

    final_risk_probability = sigmoid(logit(final))

Where:
    - prior_probability:     the case-specific starting belief BEFORE looking
                              at this event's evidence (e.g. 0.5 if you have
                              no contextual reason to favor either class yet,
                              or higher if this account/IP was already flagged)
    - historical_attack_rate: the reference base rate the two sub-models are
                              implicitly calibrated against (e.g. this
                              network segment's actual attack rate over the
                              last 30 days) — NOT the same as prior_probability;
                              this is the anchor used to convert each
                              sub-model's probability into a likelihood ratio
    - anomaly_score:          0-100 from Module 1
    - phishing_probability:   0-1 from Module 2

Degenerate case check: if anomaly_score/100 == historical_attack_rate AND
phishing_probability == historical_attack_rate (neither piece of evidence
disagrees with the base rate), then final_risk_probability collapses back to
exactly prior_probability — as it should, since neither signal added
information beyond what the base rate already encoded. This is verified in
the test suite below, not just claimed.
===============================================================================
A CORRECTION FOUND DURING VALIDATION: naive-Bayes overconfidence
===============================================================================
Bayes' rule as derived above is exact IF the two evidence channels are truly
conditionally independent given the class AND each channel's reported
probability is a noise-free calibrated estimate. In practice (verified
empirically in evaluate_bayesian_layer.py, not just asserted here), even
under a simulation deliberately built to satisfy conditional independence,
multiplying two independently-noisy likelihood ratios systematically
overshoots — producing overconfident posteriors (e.g. cases where the fused
model claims >99% risk are only right ~76% of the time in one specific
validation run). This is a well-documented property of naive Bayes fusion in
general (see Niculescu-Mizil & Caruana, "Predicting Good Probabilities With
Supervised Learning", 2005): it tends to rank cases well (AUC is preserved)
while pushing the actual probability magnitudes toward 0/1 more than the
data warrants.

The fix is standard: temperature/shrinkage scaling applied to the
likelihood-ratio terms (NOT the prior term — the prior is a genuine belief,
not noisy evidence, so it isn't dampened):

    logit(final) = logit(prior_probability)
                 + shrinkage * [ logit(anomaly_score/100) - logit(historical_attack_rate) ]
                 + shrinkage * [ logit(phishing_probability) - logit(historical_attack_rate) ]

shrinkage=1.0 recovers pure, undamped Bayes' rule (useful for testing the
formula itself — see the self-tests below, which all use shrinkage=1.0 so
they verify the actual Bayesian math, not the calibration patch on top of
it). shrinkage<1.0 dampens each evidence channel's pull on the posterior,
correcting the overconfidence. Because shrinkage is a monotonic rescaling of
the combined logit, it changes NOTHING about ranking (AUC is invariant to
it) — it only affects calibration (Brier score). Grid search on the
calibrated validation scenario found shrinkage≈0.4-0.5 minimizes Brier score
(0.047 vs 0.097 at shrinkage=1.0, beating even the naive-average baseline of
0.056). Default is set to 0.5 — a reasonable middle value, not overfit to
one simulation. In a real deployment, call calibrate_shrinkage() with actual
labeled outcomes to fit this properly, the same way temperature scaling is
normally fit on a held-out validation set rather than guessed.
"""

import numpy as np
from scipy.optimize import minimize_scalar

from utils import get_logger, safe_logit, sigmoid, classify_risk_category

logger = get_logger("bayesian_layer")

DEFAULT_SHRINKAGE = 0.5


def bayesian_risk_adjustment(anomaly_score, phishing_probability,
                              historical_attack_rate, prior_probability,
                              shrinkage: float = DEFAULT_SHRINKAGE):
    """
    Fuse Module 1's anomaly_score and Module 2's phishing_probability into a
    single posterior probability via Bayes' rule (odds multiplication, done
    in log-odds space), with a shrinkage correction for naive-Bayes
    overconfidence (see module docstring for why this is needed and how it
    was derived empirically).

    Args:
        anomaly_score: float or array-like, 0-100 (Module 1's anomaly_score)
        phishing_probability: float or array-like, 0-1 (Module 2's phishing_probability)
        historical_attack_rate: float, 0-1. The reference base rate both
            sub-model outputs are calibrated against.
        prior_probability: float or array-like, 0-1. Case-specific prior
            belief before this event's evidence is considered.
        shrinkage: float, default 0.5. Dampens each evidence channel's
            log-likelihood-ratio contribution to correct overconfidence.
            1.0 = pure, undamped Bayes' rule. Does not affect ranking/AUC —
            only calibration. Fit this against real labeled data with
            calibrate_shrinkage() when you have it.

    Returns:
        final_risk_probability: float or np.ndarray, 0-1. Public contract name.
    """
    anomaly_score = np.asarray(anomaly_score, dtype=np.float64)
    phishing_probability = np.asarray(phishing_probability, dtype=np.float64)
    prior_probability = np.asarray(prior_probability, dtype=np.float64)

    if not (0.0 < historical_attack_rate < 1.0):
        raise ValueError("historical_attack_rate must be strictly between 0 and 1.")
    if np.any((anomaly_score < 0) | (anomaly_score > 100)):
        raise ValueError("anomaly_score must be in [0, 100].")
    if np.any((phishing_probability < 0) | (phishing_probability > 1)):
        raise ValueError("phishing_probability must be in [0, 1].")
    if np.any((prior_probability < 0) | (prior_probability > 1)):
        raise ValueError("prior_probability must be in [0, 1].")

    anomaly_prob = anomaly_score / 100.0

    base_logit = safe_logit(np.array(historical_attack_rate))
    logit_prior = safe_logit(prior_probability)
    logit_anomaly = safe_logit(anomaly_prob)
    logit_phishing = safe_logit(phishing_probability)

    # log(LR_anomaly) = logit(anomaly_prob) - logit(base_rate)
    # log(LR_phishing) = logit(phishing_probability) - logit(base_rate)
    # shrinkage dampens the evidence terms only — the prior is not "noisy
    # evidence", so it passes through undamped.
    combined_logit = logit_prior \
        + shrinkage * (logit_anomaly - base_logit) \
        + shrinkage * (logit_phishing - base_logit)

    final_risk_probability = sigmoid(combined_logit)

    # Return a Python float for scalar inputs (nicer downstream ergonomics),
    # array for batch inputs.
    if final_risk_probability.ndim == 0:
        return float(final_risk_probability)
    return final_risk_probability


def calibrate_shrinkage(y_true, anomaly_score, phishing_probability,
                         historical_attack_rate, prior_probability) -> float:
    """
    Fit the Brier-optimal shrinkage value against real labeled outcomes —
    the proper way to set this parameter in production, rather than trusting
    the 0.5 default forever. Analogous to fitting temperature scaling on a
    held-out validation set.

    Args:
        y_true: array-like of 0/1 ground-truth labels
        anomaly_score, phishing_probability, historical_attack_rate,
        prior_probability: same as bayesian_risk_adjustment()

    Returns:
        The shrinkage value in [0, 1] minimizing Brier score on this data.
    """
    from sklearn.metrics import brier_score_loss

    y_true = np.asarray(y_true)

    def objective(shrinkage):
        preds = bayesian_risk_adjustment(
            anomaly_score, phishing_probability, historical_attack_rate,
            prior_probability, shrinkage=float(shrinkage),
        )
        return brier_score_loss(y_true, preds)

    result = minimize_scalar(objective, bounds=(0.01, 1.0), method="bounded")
    logger.info(f"calibrate_shrinkage: fit shrinkage={result.x:.4f} (Brier={result.fun:.4f})")
    return float(result.x)


def risk_category_from_probability(final_risk_probability: float) -> str:
    """Map final_risk_probability (0-1) to the spec'd Low/Medium/Critical bands."""
    return classify_risk_category(final_risk_probability * 100.0)


# -----------------------------------------------------------------------------
# Self-test: verify the math actually behaves like Bayesian updating, not just
# claims to. Run directly: `python bayesian_layer.py`
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    # 1. Degenerate case: evidence == base rate exactly -> posterior == prior.
    #    Holds for ANY shrinkage value, since the likelihood-ratio terms are
    #    exactly zero regardless of the multiplier — testing at both extremes.
    hist_rate = 0.10
    prior = 0.3
    for shrink in (1.0, DEFAULT_SHRINKAGE):
        result = bayesian_risk_adjustment(
            anomaly_score=hist_rate * 100, phishing_probability=hist_rate,
            historical_attack_rate=hist_rate, prior_probability=prior, shrinkage=shrink,
        )
        logger.info(f"Degenerate case (shrinkage={shrink}): expected {prior:.4f}, got {result:.4f}")
        assert abs(result - prior) < 1e-6, "Degenerate case failed — evidence should collapse to prior!"

    # 2. Strong evidence in both channels should push risk up sharply
    #    (pure Bayes, shrinkage=1.0 — testing the raw math)
    high_risk = bayesian_risk_adjustment(
        anomaly_score=95, phishing_probability=0.97,
        historical_attack_rate=0.10, prior_probability=0.10, shrinkage=1.0,
    )
    logger.info(f"Strong dual evidence (pure Bayes) -> final_risk_probability={high_risk:.4f} "
                f"({risk_category_from_probability(high_risk)})")
    assert high_risk > 0.9, "Strong dual evidence should produce high risk!"

    # 3. Weak/contradicting evidence should keep risk low (pure Bayes)
    low_risk = bayesian_risk_adjustment(
        anomaly_score=3, phishing_probability=0.01,
        historical_attack_rate=0.10, prior_probability=0.10, shrinkage=1.0,
    )
    logger.info(f"Weak dual evidence (pure Bayes) -> final_risk_probability={low_risk:.4f} "
                f"({risk_category_from_probability(low_risk)})")
    assert low_risk < 0.05, "Weak dual evidence should produce low risk!"

    # 4. Symmetry: swapping anomaly_score and phishing_probability (on
    #    comparable scales) should give the same result — neither input is
    #    silently privileged over the other. Symmetry must hold regardless
    #    of shrinkage since both evidence terms are scaled identically.
    a = bayesian_risk_adjustment(80, 0.3, 0.10, 0.10)
    b = bayesian_risk_adjustment(30, 0.8, 0.10, 0.10)
    logger.info(f"Symmetry check (default shrinkage): a={a:.4f}, b={b:.4f}")
    assert abs(a - b) < 1e-6, "Evidence fusion should be symmetric between the two channels!"

    # 5. shrinkage should not affect ranking — only calibration/magnitude.
    #    Verify default (0.5) still preserves relative ordering vs pure Bayes.
    scores_pure = bayesian_risk_adjustment(
        np.array([10, 50, 90]), np.array([0.05, 0.5, 0.95]), 0.10,
        np.array([0.1, 0.1, 0.1]), shrinkage=1.0,
    )
    scores_default = bayesian_risk_adjustment(
        np.array([10, 50, 90]), np.array([0.05, 0.5, 0.95]), 0.10,
        np.array([0.1, 0.1, 0.1]), shrinkage=DEFAULT_SHRINKAGE,
    )
    logger.info(f"Ranking check — pure Bayes: {scores_pure}, default shrinkage: {scores_default}")
    assert np.all(np.argsort(scores_pure) == np.argsort(scores_default)), \
        "Shrinkage should never change relative ranking!"

    # 6. Batch (array) inputs work
    batch_result = bayesian_risk_adjustment(
        anomaly_score=np.array([10, 50, 90]),
        phishing_probability=np.array([0.05, 0.5, 0.95]),
        historical_attack_rate=0.10,
        prior_probability=np.array([0.1, 0.1, 0.1]),
    )
    logger.info(f"Batch result (default shrinkage): {batch_result}")
    assert isinstance(batch_result, np.ndarray) and len(batch_result) == 3

    logger.info("All bayesian_layer.py self-tests passed.")
